accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('search/', views.search_profile, name='search_profile'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/follow/', views.follow, name='follow'),
    path('search/<str:username>/', views.search_profile, name='search_profile')
    
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/comments/create', views.comment_create, name='comment_create'),

    path('<int:post_id>/like/', views.like, name='like'),
    path('<int:post_id>/like-async/', views.like_async, name='like_async'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField

# Create your models here.

class User(AbstractUser):
    profile_image = ResizedImageField(
        size=[500, 500],
        crop=['middle', 'center'],
        upload_to='profile',
    )


    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)

posts/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings

# Create your models here.
class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # image = models.ImageField(upload_to='image/%Y/%m')
    image = ResizedImageField(
        size=[500, 500],
        crop=['middle', 'center'],
        upload_to='image/%Y/%m'
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # user_id = 

    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')



class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User
from django.contrib.auth import get_user_model
from django.forms import ModelForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'profile_image')


class CustomAuthenticationForm(AuthenticationForm):
    pass


class CustomProfileForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('username', )

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        exclude = ('user', 'like_users', )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm, CustomProfileForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
# from .models import User
from django.contrib.auth import get_user_model

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
        
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/form.html', context)


def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('posts:index')
        
    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/form.html', context)


def profile(request, username):
    User = get_user_model()

    user_info = User.objects.get(username=username)

    context = {
        'user_info': user_info,
    }

    return render(request, 'accounts/profile.html', context)

from django.contrib.auth.decorators import login_required

@login_required
def follow(request, username):
    User = get_user_model()

    me = request.user
    you = User.objects.get(username=username)

    if me in you.followers.all():
        me.followings.remove(you)
    else:
        me.followings.add(you)

    return redirect('accounts:profile', username=username)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')



def search_profile(request):
    
    username = request.GET.get('username')
    print(username)

    try:
        user = get_user_model().objects.get(username=username)
        return redirect('accounts:profile', username=username)
    except:
        return redirect('posts:index')

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

# Create your views here.
def index(request):
    posts = Post.objects.all().order_by('-id')
    comment_form = CommentForm()

    context = {
        'posts': posts,
        'comment_form': comment_form,
    }

    return render(request, 'index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = PostForm()

    context = {
        'form': form,
    }

    return render(request, 'form.html', context)


@login_required
def comment_create(request, post_id):
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)

        # 현재 로그인 유저
        comment.user = request.user
        # post_id를 기준으로 찾은 post
        post = Post.objects.get(id=post_id)
        comment.post = post

        comment.save()

        return redirect('posts:index')


@login_required
def like(request, post_id):

    # 좋아요 버튼을 누른 유저
    user = request.user
    post = Post.objects.get(id=post_id)

    # 이미 좋아요 버튼을 누른경우
    # if user in post.like_users.all():
    if post in user.like_posts.all():
        post.like_users.remove(user)
        # user.like_posts.remove(post)

    # 좋아요 버튼을 아직 안누른경우
    else:
        post.like_users.add(user)
        # user.like_posts.add(post)
      
    return redirect('posts:index')



from django.http import JsonResponse

def like_async(request, post_id):
    # context = {
    #     'message': post_id,
    # }


    user = request.user
    post = Post.objects.get(id=post_id)

    if user in post.like_users.all():
        post.like_users.remove(user)
        status = False
    else:
        post.like_users.add(user)
        status = True

    context = {
        'status': status,
        'count': len(post.like_users.all())
    }


    return JsonResponse(context)

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
<h1>signup</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="test">
</form>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block body %}

<div class="row">
    <div class="col-4">
        <img src="{{user_info.profile_image.url}}" alt="" class="img-fluid rounded-circle">

    </div>
    <div class="col-8">
        <div class="row">
            <div class="col-3">{{user_info.username}}</div>

            <!-- user: 로그인한 사람 / user_info: 프로필페이지 유저 -->
            {% if user != user_info%}
            <div class="col-4">
                {% if user in user_info.followers.all %}
                    <a href="{% url 'accounts:follow' username=user_info.username %}" class="btn btn-primary btn-sm">팔로우</a>
                {% else %}
                    <a href="{% url 'accounts:follow' username=user_info.username %}" class="btn btn-secondary btn-sm">팔로우</a>
                {% endif %}
            </div>
            {% endif %}

        </div>
        <div class="row">
            <div class="col">게시물 {{user_info.post_set|length}}</div>
            <div class="col">팔로워 {{user_info.followers.all|length}}</div>
            <div class="col">팔로우 {{user_info.followings.all|length}}</div>
        </div>
    </div>
</div>

<div class="row row-cols-3">

    {% for post in user_info.post_set.all %}
        <div class="col">
            <div class="card">
                <img src="{{post.image.url}}" alt="">
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

posts/templates/_card.html
{% load bootstrap5 %}
<div class="card mt-4">
    <div class="card-header">
        <p>
            <img src="{{post.user.profile_image.url}}" alt="" class="rounded-circle" width="50px">
            <a href="{% url 'accounts:profile' username=post.user %}" class="text-reset text-decoration-none">{{post.user}}</a>
        </p>
    </div>
    <img src="{{post.image.url}}" alt="..." width="300px">
    <div class="card-body">
        <!-- <h5 class="card-title"></h5> -->
        {% if post in user.like_posts.all  %}
            <i class="bi bi-heart-fill heart" style="color: red" data-post-id="{{post.id}}">{{post.like_users.all|length}}</i> 
        {% else %}
            <i class="bi bi-heart heart" data-post-id="{{post.id}}">{{post.like_users.all|length}}</i>
        {% endif %}
         명이 좋아합니다.

        <p class="card-text">{{post.content}}</p>
        <p class="card-text">{{post.created_at|timesince}}</p>
        <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
    </div>
    <div class="card-footer">
        {% if user.is_authenticated %}
        <form action="{% url 'posts:comment_create' post_id=post.id %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form comment_form%}
            <input type="submit" value="댓글 추가">
        </form>
        <hr>
        {% endif %}


        {% for comment in post.comment_set.all %}
            <li>{{comment.user}} : {{comment.content}}</li>
        {% endfor %}
    </div>

</div>

  </div>

posts/templates/form.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="당신의 일상을 공유하세요!">
    </form>

{% endblock %}

posts/templates/index.html
{% extends 'base.html' %}

{% block body %}

    {% for post in posts %}
        {% include '_card.html' %}
    {% endfor %}

    <script>    
        const likeButtons = document.querySelectorAll('i.heart')
        // console.log(likeButtons)

        likeButtons.forEach((likeButton)=>{
            likeButton.addEventListener('click', (event)=> {
                let postId = event.target.dataset.postId

                likeRequest(event.target, postId)
            })
        })

        let likeRequest = async (button, postId) => {
            // console.log(button, postId)
            // django 서버에 요청을 보낸다
            let likeURL = `/posts/${postId}/like-async/`
            let response = await fetch(likeURL)
            let result = await response.json()

            console.log(result)

            // django 서버의 응답에 따라 좋아요 버튼을 수정한다.
            if (result.status) {
                // true > 좋아요가 눌린 경우
                button.classList.remove('bi-heart')
                button.classList.add('bi-heart-fill')
                button.style.color = 'red'
                button.innerHTML = result.count

            } else {
                // false > 좋아요 취소
                button.classList.remove('bi-heart-fill')
                button.classList.add('bi-heart')
                button.style.color = 'black'
                button.innerHTML = result.count
            }

        }
    </script>

{% endblock %}

templates/_nav.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Google Icon -->
    <link
            href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
            rel="stylesheet">

    <!-- Jquery -->
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>

    <title>Hyosung's insta develop</title>

    <style>
        .box {
            width: 150px;
            height: 150px;
            border-radius: 70%;
            overflow: hidden;
        }

        .profile {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .feed_box {
            margin: 20px 0;
            border: solid 1px gray;
            background-color: white
        }

        .modal_overlay {
            width: 100%;
            height: 100%;
            position: absolute;
            left: 0;
            top: 0;
            display: none;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            background: rgba(0, 0, 0, 0.8);
            backdrop-filter: blur(1.5px);
            -webkit-backdrop-filter: blur(1.5px);
            z-index: 10000;
        }

        .modal_window {
            background: white;
            backdrop-filter: blur(13.5px);
            -webkit-backdrop-filter: blur(13.5px);
            border-radius: 10px;
            border: 1px solid rgba(255, 255, 255, 0.18);
            width: 800px;
            height: 600px;
            position: relative;
            padding: 10px;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="position: fixed;width: 100%; z-index: 999">
    <div class="container-fluid" style="justify-content: space-between;flex-wrap: nowrap; min-width: 1000px">
        <a class="navbar-brand" href="{% url 'posts:index' %}"><img style="width: 100px"
                                                 src="https://www.instagram.com/static/images/web/mobile_nav_type_logo-2x.png/1b47f9d0e595.png">
        </a>
        <form action="{% url 'accounts:search_profile' %}" method="GET"> 
          <input class="form-control me-2" style="width: 400px;display: inline;" type="search" placeholder="Search" aria-label="Search" name="username">
          <input type="submit" value="찾아보기">
        </form>
        <div style="display: flex">
            <a href="{% url 'accounts:profile' username=user %}" style="color: black"><span class="material-icons"
                                                      style="padding-right: 10px"> home </span></a>
            <a href="{% url 'posts:create' %}" style="color: black"><span class="bi bi-plus-circle"
                                                        style="padding-right: 10px"> </span></a>
            <a href="{% url 'accounts:logout' %}" style="color: black"><span class="bi bi-x-lg"
                                                          style="padding-right: 10px"></span></a>

                                                        
            <!-- <span id="nav_bar_add_box" class="material-icons-outlined" style="padding-right: 10px" a class="nav-link" href="{% url 'posts:create' %}">add_box</span> -->

                    </div>
                </a>

                <!-- <ul class="dropdown-menu" style="left:-158px" aria-labelledby="dropdownMenuLink">
                    <li><a class="dropdown-item" href="/content/profile">프로필</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="/user/logout">로그아웃</a></li>
                </ul> -->
                <html>
                  <body style="background-color:#F2F2F2">
                  </body>
                </html>
            </div>
        </div>
    </div>
</nav>




<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'posts:index' %}">HOME</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'posts:create' %}">Create</a>
          <a class="nav-link" href="{% url 'accounts:profile' username=user %}">{{user}}</a>

          {% else %}
          <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>

          {% endif %}


          <nav class="navbar bg-body-tertiary">
            <form class="container-fluid">
              <div class="input-group">
                <span class="input-group-text" id="basic-addon1">@</span>
                <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
              </div>
            </form>
          </nav>
        </div>
      </div>
    </div>
  </nav>

</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>

    {% include '_nav.html' %}


    <div class="container">
        {% block body %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>